name: waldo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pinocchio=3.1.0
  - numpy=1.26.4
  - aiohttp
  - aiohttp-cors
  - conda-pack
  - libstdcxx-ng  # C++ runtime for native extensions
